### ISSUE TITLE
Phantom JS/Webshot not working as expected on new rstudio

### ISSUE THREAD

**Issue by RobinL** [ministryofjustice/analytics-platform-rstudio#35]
To recreate problem, run :

```
> webshot::webshot("http://www.google.com")
QXcbConnection: Could not connect to display :0
PhantomJS has crashed. Please read the bug reporting guide at
```

Is this because of the changes in the new Dockerfile?

Previously it was:
https://github.com/ministryofjustice/analytics-platform-rstudio/blob/ac7c9e4fb6bf8dfab3b6af0b89e1afc4c1b7681e/Dockerfile#L179

```
  && R -e "install.packages('webshot')" \
  && R -e "webshot::install_phantomjs()" \
  && mv /root/bin/phantomjs /usr/bin/phantomjs \
  && chmod a+rx /usr/bin/phantomjs
```

Now it's 
https://github.com/ministryofjustice/analytics-platform-rstudio/blob/8179a5aa7c7faa09f0819eeed60f4ed98fa8c40f/Dockerfile#L81
```
ENV PHANTOMJS_VERSION="2.1.1+dfsg-2"
--
  # Dependency of R package Webshot
    phantomjs=$PHANTOMJS_VERSION; \

--
&& R -e "install.packages('webshot')"

``

**Comment by RobinL** [comment]
I've verified that adding:

```
&& R -e "webshot::install_phantomjs()" \
    && mv /root/bin/phantomjs /usr/bin/phantomjs \
    && chmod a+rx /usr/bin/phantomjs
``` 

following 
```
 && R -e "install.packages('webshot')" \
```

fixes this

**Comment by djsd123** [comment]
Thanks for looking into this.  Your suggestion appears to be the correct way to install PhatomJS for webshot.
