### ISSUE TITLE
Add python module ezodf

### ISSUE THREAD

**Issue by Thomas-Hirsch** [ministryofjustice/analytics-platform-rstudio#47]
It would be useful to be able to read .ods files in R, since that's the format a lot of government statistical publications are now being published in. However, the R package `readODS` is (currently) extremely slow, particularly for large spreadsheets. The python module ezodf seems to be much faster, so it would be useful to be able to access it through R via reticulate.

If there's a better R package/method for reading .ods files, that would of course be preferred.

**Comment by Thomas-Hirsch** [comment]
Evidently you can install python modules from the terminal, using the command `python -m pip install --user ezodf`, so no need to install on a system level (I may make a wrapper package like dbtools to help facilitate this for others). Naturally a decent native package solution would be preferred.

**Comment by xoen** [comment]
@Thomas-Hirsch should we close this then?

**Comment by Thomas-Hirsch** [comment]
Yeah I think so
